// Interface automatically generated by schemas-to-ts

import { Product } from '../../../product/content-types/product/product';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Product_Plain } from '../../../product/content-types/product/product';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ProductVariant {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    unit_price?: number;
    product?: { data: Product };
    is_default?: boolean;
    stock?: number;
    units_per_stock?: number;
    image?: { data: Media };
  };
}
export interface ProductVariant_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  unit_price?: number;
  product?: Product_Plain;
  is_default?: boolean;
  stock?: number;
  units_per_stock?: number;
  image?: Media;
}

export interface ProductVariant_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  unit_price?: number;
  product?: number;
  is_default?: boolean;
  stock?: number;
  units_per_stock?: number;
  image?: number;
}

export interface ProductVariant_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  unit_price?: number;
  product?: AdminPanelRelationPropertyModification<Product_Plain>;
  is_default?: boolean;
  stock?: number;
  units_per_stock?: number;
  image?: AdminPanelRelationPropertyModification<Media>;
}
