// Interface automatically generated by schemas-to-ts

import { ProductProperty } from '../../../api/product-property/content-types/product-property/product-property';
import { ProductProperty_Plain } from '../../../api/product-property/content-types/product-property/product-property';

export interface CartItemProperties {
  product_property?: { data: ProductProperty };
  quantity: number;
}
export interface CartItemProperties_Plain {
  product_property?: ProductProperty_Plain;
  quantity: number;
}

export interface CartItemProperties_NoRelations {
  product_property?: number;
  quantity: number;
}

