// Interface automatically generated by schemas-to-ts

import { ProductVariant } from '../../../api/product-variant/content-types/product-variant/product-variant';
import { CartItemProperties } from './CartItemProperties';
import { ProductVariant_Plain } from '../../../api/product-variant/content-types/product-variant/product-variant';
import { CartItemProperties_Plain } from './CartItemProperties';
import { CartItemProperties_NoRelations } from './CartItemProperties';

export interface Variant {
  product_variant?: { data: ProductVariant };
  quantity: number;
  properties: CartItemProperties[];
}
export interface Variant_Plain {
  product_variant?: ProductVariant_Plain;
  quantity: number;
  properties: CartItemProperties_Plain[];
}

export interface Variant_NoRelations {
  product_variant?: number;
  quantity: number;
  properties: CartItemProperties_NoRelations[];
}

