// Interface automatically generated by schemas-to-ts

import { Product } from '../../../product/content-types/product/product';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Product_Plain } from '../../../product/content-types/product/product';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ProductReview {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    user_email: string;
    rating: number;
    comment?: string;
    product?: { data: Product };
    attachments?: { data: Media[] };
    user_name: string;
  };
}
export interface ProductReview_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  user_email: string;
  rating: number;
  comment?: string;
  product?: Product_Plain;
  attachments?: Media[];
  user_name: string;
}

export interface ProductReview_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  user_email: string;
  rating: number;
  comment?: string;
  product?: number;
  attachments?: number[];
  user_name: string;
}

export interface ProductReview_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  user_email: string;
  rating: number;
  comment?: string;
  product?: AdminPanelRelationPropertyModification<Product_Plain>;
  attachments?: AdminPanelRelationPropertyModification<Media>[];
  user_name: string;
}
