// Interface automatically generated by schemas-to-ts

export interface Order {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    totalCost?: number;
    totalItems?: number;
    userName?: string;
    stripeSessionId?: string;
    products?: any;
  };
}
export interface Order_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  totalCost?: number;
  totalItems?: number;
  userName?: string;
  stripeSessionId?: string;
  products?: any;
}

export interface Order_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  totalCost?: number;
  totalItems?: number;
  userName?: string;
  stripeSessionId?: string;
  products?: any;
}

export interface Order_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  totalCost?: number;
  totalItems?: number;
  userName?: string;
  stripeSessionId?: string;
  products?: any;
}
