// Interface automatically generated by schemas-to-ts

import { Cart } from '../../../cart/content-types/cart/cart';
import { Cart_Plain } from '../../../cart/content-types/cart/cart';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum PaymentStatus {
  Pending = 'pending',
  Success = 'success',
  Cancelled = 'cancelled',}

export interface Order {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    total: number;
    cart?: { data: Cart };
    payment_session_id: string;
    payment_status: PaymentStatus;
    shipping_address?: string;
    tracking_url_provider?: string;
    label_url?: string;
    customer_experience?: string;
    user_email?: string;
    label_is_printed?: boolean;
  };
}
export interface Order_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  total: number;
  cart?: Cart_Plain;
  payment_session_id: string;
  payment_status: PaymentStatus;
  shipping_address?: string;
  tracking_url_provider?: string;
  label_url?: string;
  customer_experience?: string;
  user_email?: string;
  label_is_printed?: boolean;
}

export interface Order_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  total: number;
  cart?: number;
  payment_session_id: string;
  payment_status: PaymentStatus;
  shipping_address?: string;
  tracking_url_provider?: string;
  label_url?: string;
  customer_experience?: string;
  user_email?: string;
  label_is_printed?: boolean;
}

export interface Order_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  total: number;
  cart?: AdminPanelRelationPropertyModification<Cart_Plain>;
  payment_session_id: string;
  payment_status: PaymentStatus;
  shipping_address?: string;
  tracking_url_provider?: string;
  label_url?: string;
  customer_experience?: string;
  user_email?: string;
  label_is_printed?: boolean;
}
