// Interface automatically generated by schemas-to-ts

import { Product } from '../../../product/content-types/product/product';
import { Product_Plain } from '../../../product/content-types/product/product';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  Recurring = 'recurring',
  OneTime = 'one_time',}
export enum DiscountUnit {
  Fiat = 'fiat',
  Percentage = 'percentage',}
export enum RecurringInterval {
  Day = 'day',
  Week = 'week',
  Month = 'month',
  Year = 'year',}

export interface PurchaseOption {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    type: Type;
    has_discount?: boolean;
    discount_value?: number;
    discount_unit?: DiscountUnit;
    products?: { data: Product[] };
    recurring_interval?: RecurringInterval;
    recurring_interval_count?: number;
  };
}
export interface PurchaseOption_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  type: Type;
  has_discount?: boolean;
  discount_value?: number;
  discount_unit?: DiscountUnit;
  products?: Product_Plain[];
  recurring_interval?: RecurringInterval;
  recurring_interval_count?: number;
}

export interface PurchaseOption_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  type: Type;
  has_discount?: boolean;
  discount_value?: number;
  discount_unit?: DiscountUnit;
  products?: number[];
  recurring_interval?: RecurringInterval;
  recurring_interval_count?: number;
}

export interface PurchaseOption_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  type: Type;
  has_discount?: boolean;
  discount_value?: number;
  discount_unit?: DiscountUnit;
  products?: AdminPanelRelationPropertyModification<Product_Plain>;
  recurring_interval?: RecurringInterval;
  recurring_interval_count?: number;
}
