// Interface automatically generated by schemas-to-ts

export interface UrlShortner {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    short_code: string;
    url: string;
    visits: number;
  };
}
export interface UrlShortner_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  short_code: string;
  url: string;
  visits: number;
}

export interface UrlShortner_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  short_code: string;
  url: string;
  visits: number;
}

export interface UrlShortner_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  short_code: string;
  url: string;
  visits: number;
}
