// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { ProductVariant } from '../../../product-variant/content-types/product-variant/product-variant';
import { ProductProperty } from '../../../product-property/content-types/product-property/product-property';
import { ProductVariant_Plain } from '../../../product-variant/content-types/product-variant/product-variant';
import { ProductProperty_Plain } from '../../../product-property/content-types/product-property/product-property';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Units {
  Oz = 'oz',
  FlOz = 'Fl oz',}
export enum Category {
  Gel = 'Gel',
  Dry = 'Dry',
  Clothing = 'Clothing',
  Accessory = 'Accessory',}

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    description?: string;
    images: { data: Media[] };
    videos?: { data: Media[] };
    weight?: number;
    units?: Units;
    category?: Category;
    certifications?: string;
    healthBenefits?: string;
    ingredients?: string;
    countryOfOrigin?: string;
    dimensions?: string;
    sku?: string;
    batchNumber?: string;
    upc?: string;
    expirationDate?: Date;
    tipsForStorage?: string;
    slug: string;
    product_variants: { data: ProductVariant[] };
    thumbnail?: { data: Media };
    variant_selection_text?: string;
    unit_property_selection_text?: string;
    product_properties: { data: ProductProperty[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  images: Media[];
  videos?: Media[];
  weight?: number;
  units?: Units;
  category?: Category;
  certifications?: string;
  healthBenefits?: string;
  ingredients?: string;
  countryOfOrigin?: string;
  dimensions?: string;
  sku?: string;
  batchNumber?: string;
  upc?: string;
  expirationDate?: Date;
  tipsForStorage?: string;
  slug: string;
  product_variants: ProductVariant_Plain[];
  thumbnail?: Media;
  variant_selection_text?: string;
  unit_property_selection_text?: string;
  product_properties: ProductProperty_Plain[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  images: number[];
  videos?: number[];
  weight?: number;
  units?: Units;
  category?: Category;
  certifications?: string;
  healthBenefits?: string;
  ingredients?: string;
  countryOfOrigin?: string;
  dimensions?: string;
  sku?: string;
  batchNumber?: string;
  upc?: string;
  expirationDate?: Date;
  tipsForStorage?: string;
  slug: string;
  product_variants: number[];
  thumbnail?: number;
  variant_selection_text?: string;
  unit_property_selection_text?: string;
  product_properties: number[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  images: AdminPanelRelationPropertyModification<Media>[];
  videos?: AdminPanelRelationPropertyModification<Media>[];
  weight?: number;
  units?: Units;
  category?: Category;
  certifications?: string;
  healthBenefits?: string;
  ingredients?: string;
  countryOfOrigin?: string;
  dimensions?: string;
  sku?: string;
  batchNumber?: string;
  upc?: string;
  expirationDate?: Date;
  tipsForStorage?: string;
  slug: string;
  product_variants: AdminPanelRelationPropertyModification<ProductVariant_Plain>;
  thumbnail?: AdminPanelRelationPropertyModification<Media>;
  variant_selection_text?: string;
  unit_property_selection_text?: string;
  product_properties: AdminPanelRelationPropertyModification<ProductProperty_Plain>;
}
