// Interface automatically generated by schemas-to-ts

import { Product } from '../../../product/content-types/product/product';
import { Cart } from '../../../cart/content-types/cart/cart';
import { Product_Plain } from '../../../product/content-types/product/product';
import { Cart_Plain } from '../../../cart/content-types/cart/cart';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface CartItem {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    product?: { data: Product };
    quantity?: number;
    cart?: { data: Cart };
  };
}
export interface CartItem_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  product?: Product_Plain;
  quantity?: number;
  cart?: Cart_Plain;
}

export interface CartItem_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  product?: number;
  quantity?: number;
  cart?: number;
}

export interface CartItem_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  product?: AdminPanelRelationPropertyModification<Product_Plain>;
  quantity?: number;
  cart?: AdminPanelRelationPropertyModification<Cart_Plain>;
}
